name: Run Hive Queries

on:
  push:
    paths:
      - 'hive-scripts/*.hql'

jobs:
  run-hive:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize Hive Metastore
        run: |
          echo "Initializing Hive metastore..."
          schematool -initSchema -dbType derby || echo "Already initialized"

      - name: Run Hive Script
        run: |
          echo "Loading environment..."
          source ~/.bashrc

          echo "Checking Hive..."
          which hive
          hive --version

          echo "Running Hive queries..."
          for file in hive-scripts/*.hql
          do
            echo "Executing $file"
            hive -f $file
          done