name: Working Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show files
        run: |
          echo "Project files:"
          ls
          echo "Scripts folder:"
          ls scripts

      - name: Success message
        run: echo "Pipeline successfully running "